Import('env')
env.Append(CPPPATH=['.'])
env.Append(CPPPATH=['../mem'])
env.Append(CPPPATH=['../util'])
env.Append(CPPPATH=['../geometry'])
env.Append(CCFLAGS=['-fopenmp'])

env.Library('mesh', ['SurfaceTopology.cc', 'SurfaceTopologyOutput.cc', 'KdItem.cc', 'KdNode.cc', 'KdTree.cc', 'RegularMesh.cc'])

